# Generated by Django 4.1.5 on 2023-01-07 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('lyric', models.TextField()),
                ('tone', models.CharField(max_length=200)),
                ('cipher', models.CharField(max_length=200)),
                ('bpm', models.IntegerField()),
                ('video', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('spotify', models.CharField(max_length=200)),
                ('ytmusic', models.CharField(max_length=200)),
                ('deezer', models.CharField(max_length=200)),
                ('amazon', models.CharField(max_length=200)),
                ('matters', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
