# Generated by Django 4.1.5 on 2023-01-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='amazon',
        ),
        migrations.RemoveField(
            model_name='song',
            name='deezer',
        ),
    ]
