# Generated by Django 4.1.5 on 2023-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_amazon_remove_song_deezer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
