# Generated by Django 4.1.5 on 2023-01-10 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('songs', '0003_song_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='acoustic_guitar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='bass',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='drums',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='electric_guitar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='extra_voice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='keyboard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='playback',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='voices',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='featured_image',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
