# Generated by Django 4.1.5 on 2023-01-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='instrumental_file',
            field=models.ImageField(blank=True, upload_to='images/instrumental/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='song',
            name='voice_file',
            field=models.ImageField(blank=True, upload_to='images/voices/%d/%m/%Y/'),
        ),
    ]
